let arrayProductos = [
  {codigo: 1,
   nombre: `Iphone 7`,
   precio: 5000,
   stock: 1,
   imagen: `imagenes/accesorios/iphone.jpeg`,
   descripcion: " Estado Impecable "},
  {codigo: 2,
   nombre: `Iphone 7 plus`,
   precio: 4500,
   stock: 1,
   imagen: `imagenes/accesorios/iphone2.jpeg`,
   descripcion: " Estado Impecable "},
  {codigo: 19,
   nombre: `LG en reparacion`,
   precio: 10000,
   stock: 1,
   imagen: `imagenes/accesorios/Gale-3.png`,
   descripcion: " Estado Impecable "},
  {codigo: 4,
   nombre: `Samsung`,
   precio: 20000,
   stock: 1,
   imagen: `imagenes/accesorios/Gale-1.png`,
   descripcion: " Estado Impecable "},
  {codigo: 5,
   nombre: `Bateria`,
   precio: 1000,
   stock: 1,
   imagen: `imagenes/accesorios/Gale-3.png`,
   descripcion: " Estado Impecable "},
 
];

